/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoclik.pagamento;

import infoclik.fachada.Fachada;
import java.awt.EventQueue;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cledson
 */
public class TelaCadastroPagamento extends javax.swing.JFrame {
public JFrame frmCadastroPagamento;
    /**
     * Creates new form TelaCadastropagamento
     */
    public TelaCadastroPagamento() {
        initComponents();
    }
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaCadastroPagamento frame = new TelaCadastroPagamento();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOut1 = new javax.swing.JLabel();
        jTextFieldOut1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelId_aluno = new javax.swing.JLabel();
        jTextFieldId_aluno = new javax.swing.JTextField();
        jLabelId_aluno1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMar = new javax.swing.JLabel();
        jTextFieldMar = new javax.swing.JTextField();
        jLabelAbr = new javax.swing.JLabel();
        jTextFieldAbr = new javax.swing.JTextField();
        jLabelMai = new javax.swing.JLabel();
        jTextFieldMai = new javax.swing.JTextField();
        jLabelJun = new javax.swing.JLabel();
        jTextFieldJun = new javax.swing.JTextField();
        jLabelJul = new javax.swing.JLabel();
        jTextFieldJul = new javax.swing.JTextField();
        jTextFieldAgosto = new javax.swing.JTextField();
        jLabelSet = new javax.swing.JLabel();
        jTextFieldset = new javax.swing.JTextField();
        jLabelOut = new javax.swing.JLabel();
        jTextFieldOut = new javax.swing.JTextField();
        jLabelNov = new javax.swing.JLabel();
        jTextFieldNov = new javax.swing.JTextField();
        jLabelDez = new javax.swing.JLabel();
        jTextFieldDez = new javax.swing.JTextField();
        jLabelJan = new javax.swing.JLabel();
        jTextFieldJan = new javax.swing.JTextField();
        jLabelFev = new javax.swing.JLabel();
        jTextFieldFev = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelId_aluno2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabelOut1.setText("Outubro:");

        jLabel9.setText("X");

        jLabelId_aluno.setText("Código do aluno:");

        jTextFieldId_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldId_alunoActionPerformed(evt);
            }
        });

        jLabelId_aluno1.setText("Código do aluno:");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Pagamento");

        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelMar.setText("Março:");

        jLabelAbr.setText("Abril:");

        jLabelMai.setText("Maio:");

        jTextFieldMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaiActionPerformed(evt);
            }
        });

        jLabelJun.setText("Junho:");

        jLabelJul.setText("Julho:");

        jLabelSet.setText("Setembro:");

        jLabelOut.setText("Outubro:");

        jLabelNov.setText("Novembro:");

        jLabelDez.setText("Dezembro:");

        jLabelJan.setText("Janeiro:");

        jLabelFev.setText("Fevereiro");

        jTextFieldFev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFevActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jLabelId_aluno2.setText("Código do aluno:");

        jLabel2.setText("Agosto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId_aluno2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNov)
                                    .addComponent(jLabelJul)
                                    .addComponent(jLabelMar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNov, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDez))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldJul, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAbr)
                                            .addComponent(jLabel2))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldDez, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelJan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldJan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAbr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSet)
                                            .addComponent(jLabelMai))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFev)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldFev, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelOut)
                                            .addComponent(jLabelJun))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldJun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldOut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldJun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJun)
                            .addComponent(jTextFieldMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMai)
                            .addComponent(jTextFieldAbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAbr)
                            .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSet)
                            .addComponent(jTextFieldset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelOut)
                            .addComponent(jTextFieldOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJul))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNov)
                    .addComponent(jTextFieldNov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDez)
                    .addComponent(jTextFieldDez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJan)
                    .addComponent(jTextFieldJan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFev)
                    .addComponent(jTextFieldFev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId_aluno2)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonCadastrar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaiActionPerformed

    private void jTextFieldFevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFevActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        cadastroPagamento();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldId_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldId_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldId_alunoActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbr;
    private javax.swing.JLabel jLabelDez;
    private javax.swing.JLabel jLabelFev;
    private javax.swing.JLabel jLabelId_aluno;
    private javax.swing.JLabel jLabelId_aluno1;
    private javax.swing.JLabel jLabelId_aluno2;
    private javax.swing.JLabel jLabelJan;
    private javax.swing.JLabel jLabelJul;
    private javax.swing.JLabel jLabelJun;
    private javax.swing.JLabel jLabelMai;
    private javax.swing.JLabel jLabelMar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNov;
    private javax.swing.JLabel jLabelOut;
    private javax.swing.JLabel jLabelOut1;
    private javax.swing.JLabel jLabelSet;
    private javax.swing.JTextField jTextFieldAbr;
    private javax.swing.JTextField jTextFieldAgosto;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDez;
    private javax.swing.JTextField jTextFieldFev;
    private javax.swing.JTextField jTextFieldId_aluno;
    private javax.swing.JTextField jTextFieldJan;
    private javax.swing.JTextField jTextFieldJul;
    private javax.swing.JTextField jTextFieldJun;
    private javax.swing.JTextField jTextFieldMai;
    private javax.swing.JTextField jTextFieldMar;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNov;
    private javax.swing.JTextField jTextFieldOut;
    private javax.swing.JTextField jTextFieldOut1;
    private javax.swing.JTextField jTextFieldset;
    // End of variables declaration//GEN-END:variables


private void limparCampos() {
 jTextFieldNome.setText("");
 jTextFieldMar.setText("");
 jTextFieldAbr.setText("");
 jTextFieldMai.setText("");
 jTextFieldJun.setText("");
 jTextFieldJul.setText("");
 jTextFieldAgosto.setText("");
jTextFieldset.setText("");
jTextFieldOut.setText("");
jTextFieldNov.setText("");
jTextFieldDez.setText("");
jTextFieldJan.setText("");
jTextFieldFev.setText("");
jTextFieldCodigo.setText("");        
    }

    private void cadastroPagamento() {
        
String nome =  jTextFieldNome.getText();
String mar =  jTextFieldMar.getText();
String abr =   jTextFieldAbr.getText();
String mai = jTextFieldMai.getText();
String jun = jTextFieldJun.getText();
String jul = jTextFieldJul.getText();
String ago = jTextFieldAgosto.getText();
String set = jTextFieldset.getText();
String out = jTextFieldOut.getText(); 
String nov = jTextFieldNov.getText();
String dez = jTextFieldDez.getText();
String jan = jTextFieldJan.getText();
String fev = jTextFieldFev.getText();
String cod = jTextFieldCodigo.getText();


int id_aluno = Integer.parseInt(cod);


Pagamento pagamento = new Pagamento(nome, mar, abr, mai, jun, jul, ago, set, out, nov, dez, jan, fev, id_aluno);

    
    try {
	
		Fachada.getInstance().pagamentoCadastrar(pagamento);
		
		JOptionPane.showMessageDialog(frmCadastroPagamento, "Cadastro Realizado com sucesso!");
	         this.limparCampos();
	
	
	} catch (infoclik.pagamento.CampoObrigatorioException e) {
		JOptionPane.showMessageDialog(frmCadastroPagamento, e.getMessage(), " ERRO " , JOptionPane.ERROR_MESSAGE);
	} catch (SQLException e) {
		JOptionPane.showMessageDialog(frmCadastroPagamento, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
	}catch (Exception e){
		JOptionPane.showMessageDialog(frmCadastroPagamento, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
	}

    
    }





}

