/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoclik.pagamento;

import infoclik.fachada.Fachada;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cledson
 */
public class TelaBuscarPagamentoId extends javax.swing.JFrame {
public JFrame frmProcurarAluno;
    /**
     * Creates new form TelaCadastropagamento
     */
    public TelaBuscarPagamentoId() {
        initComponents();
    }
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaBuscarPagamentoId frame = new TelaBuscarPagamentoId();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOut1 = new javax.swing.JLabel();
        jTextFieldOut1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMar = new javax.swing.JLabel();
        jTextFieldMar = new javax.swing.JTextField();
        jLabelAbr = new javax.swing.JLabel();
        jTextFieldAbr = new javax.swing.JTextField();
        jLabelMai = new javax.swing.JLabel();
        jTextFieldMai = new javax.swing.JTextField();
        jLabelJun = new javax.swing.JLabel();
        jTextFieldJun = new javax.swing.JTextField();
        jLabelJul = new javax.swing.JLabel();
        jTextFieldJul = new javax.swing.JTextField();
        jLabelAgosto = new javax.swing.JLabel();
        jTextFieldAgosto = new javax.swing.JTextField();
        jLabelSet = new javax.swing.JLabel();
        jTextFieldset = new javax.swing.JTextField();
        jLabelOut = new javax.swing.JLabel();
        jTextFieldOut = new javax.swing.JTextField();
        jLabelNov = new javax.swing.JLabel();
        jTextFieldNov = new javax.swing.JTextField();
        jLabelDez = new javax.swing.JLabel();
        jTextFieldDez = new javax.swing.JTextField();
        jLabelJan = new javax.swing.JLabel();
        jTextFieldJan = new javax.swing.JTextField();
        jLabelFev = new javax.swing.JLabel();
        jTextFieldFev = new javax.swing.JTextField();
        jLabelId_aluno = new javax.swing.JLabel();
        jTextFieldId_aluno = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelId_aluno1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        jLabelOut1.setText("Outubro:");

        jLabel9.setText("X");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Pagamento por código");

        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelMar.setText("Março:");

        jLabelAbr.setText("Abril:");

        jLabelMai.setText("Maio:");

        jLabelJun.setText("Junho:");

        jLabelJul.setText("Julho:");

        jLabelAgosto.setText("Agosto:");

        jLabelSet.setText("Setembro:");

        jLabelOut.setText("Outubro:");

        jLabelNov.setText("Novembro:");

        jLabelDez.setText("Dezembro:");

        jLabelJan.setText("Janeiro:");

        jLabelFev.setText("Fevereiro");

        jLabelId_aluno.setText("Código do aluno:");

        jTextFieldId_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldId_alunoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabelId_aluno1.setText("Código do aluno:");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJul)
                            .addComponent(jLabelNov)
                            .addComponent(jLabelMar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldJul, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNov, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAgosto)
                            .addComponent(jLabelDez)
                            .addComponent(jLabelAbr))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDez, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelJan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAbr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMai)
                                    .addComponent(jLabelSet))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldJan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFev)
                            .addComponent(jLabelOut)
                            .addComponent(jLabelJun))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFev, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId_aluno1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar)
                                .addGap(18, 137, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelId_aluno)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldId_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonAtualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonExcluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimpar)))
                                .addGap(18, 18, 18)))
                        .addComponent(jButtonSair)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jLabelId_aluno1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMar)
                            .addComponent(jLabelAbr)
                            .addComponent(jTextFieldAbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMai)
                            .addComponent(jTextFieldMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJun)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJul)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSet)
                            .addComponent(jTextFieldset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOut)
                            .addComponent(jTextFieldAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAgosto)
                            .addComponent(jTextFieldJul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelJan)
                        .addComponent(jTextFieldJan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFev)
                        .addComponent(jTextFieldFev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNov)
                        .addComponent(jTextFieldNov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDez)
                        .addComponent(jTextFieldDez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId_aluno)
                    .addComponent(jTextFieldId_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonLimpar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldId_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldId_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldId_alunoActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
               try{
					String nome = jTextFieldNome.getText();
					Fachada fachada = Fachada.getInstance();
					Pagamento pagamento = fachada.pagamentoProcurar(nome);
					
                                        
                                       
                                        pagamento.setNome(jTextFieldNome.getText());
                                        pagamento.setMar(jTextFieldMar.getText());
                                        pagamento.setAbr(jTextFieldAbr.getText());
                                        pagamento.setMai(jTextFieldMai.getText());
                                        pagamento.setJun(jTextFieldJun.getText());
                                        pagamento.setJul(jTextFieldJul.getText());
                                        pagamento.setAgo(jTextFieldAgosto.getText());
                                        pagamento.setSet(jTextFieldset.getText());
                                        pagamento.setOut(jTextFieldOut.getText());
                                        pagamento.setNov(jTextFieldNov.getText());
                                        pagamento.setDez(jTextFieldDez.getText());
                                        pagamento.setJan(jTextFieldJan.getText());
                                        pagamento.setFev(jTextFieldFev.getText());
                                       
                 
					fachada.pagamentoAtualizar(pagamento);
					
				} catch (PagamentoNaoEncontradoException e1){
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
				} catch (infoclik.aluno.CampoObrigatorioException e1) {
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO " , JOptionPane.ERROR_MESSAGE);
				
				}catch (Exception e1){
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
				} 

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
          String id_aluno = jTextFieldCodigo.getText();
				try {
					
					Fachada.getInstance().pagamentoProcurarId(Integer.parseInt(id_aluno));
					Fachada fachada = Fachada.getInstance();
					Pagamento temp = fachada.pagamentoProcurarId(Integer.parseInt(id_aluno));
                                        
                                        
                                        jTextFieldNome.setText(temp.getNome());
                                        jTextFieldMar.setText(temp.getMar());
                                        jTextFieldAbr.setText(temp.getAbr());
                                        jTextFieldMai.setText(temp.getMai());
                                        jTextFieldJun.setText(temp.getJun());
                                        jTextFieldJul.setText(temp.getJul());
                                        jTextFieldAgosto.setText(temp.getAgo());
                                        jTextFieldset.setText(temp.getSet());
                                        jTextFieldOut.setText(temp.getOut());
                                        jTextFieldNov.setText(temp.getNov());
                                        jTextFieldDez.setText(temp.getDez());
                                        jTextFieldJan.setText(temp.getJan());
                                        jTextFieldFev.setText(temp.getFev());
					jTextFieldId_aluno.setText(Integer.toString(temp.getId_aluno()));
					
					
					

				
				} catch (PagamentoNaoEncontradoException e1){
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
				} catch (infoclik.aluno.CampoObrigatorioException e1) {
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO " , JOptionPane.ERROR_MESSAGE);
				}catch (Exception e1){
					JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
				} 
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resultado = JOptionPane.showConfirmDialog(frmProcurarAluno, "Deseja Excluir?\n" +jTextFieldCodigo.getText(),"Excluir",JOptionPane.YES_NO_CANCEL_OPTION);
				if(resultado == JOptionPane.YES_OPTION){
					try {
						String id_aluno = jTextFieldCodigo.getText();
						Fachada.getInstance().pagamentoRemoverId(Integer.parseInt(id_aluno));
						Fachada fachada = Fachada.getInstance();
						JOptionPane.showMessageDialog(frmProcurarAluno, "Removido com Sucesso!");
			
						
					
					} catch (PagamentoNaoEncontradoException e1){
						JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
					} catch (infoclik.pagamento.CampoObrigatorioException e1) {
						JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), " ERRO " , JOptionPane.ERROR_MESSAGE);
					}catch (Exception e1){
						JOptionPane.showMessageDialog(frmProcurarAluno, e1.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
					} 
				
				}
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbr;
    private javax.swing.JLabel jLabelAgosto;
    private javax.swing.JLabel jLabelDez;
    private javax.swing.JLabel jLabelFev;
    private javax.swing.JLabel jLabelId_aluno;
    private javax.swing.JLabel jLabelId_aluno1;
    private javax.swing.JLabel jLabelJan;
    private javax.swing.JLabel jLabelJul;
    private javax.swing.JLabel jLabelJun;
    private javax.swing.JLabel jLabelMai;
    private javax.swing.JLabel jLabelMar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNov;
    private javax.swing.JLabel jLabelOut;
    private javax.swing.JLabel jLabelOut1;
    private javax.swing.JLabel jLabelSet;
    private javax.swing.JTextField jTextFieldAbr;
    private javax.swing.JTextField jTextFieldAgosto;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDez;
    private javax.swing.JTextField jTextFieldFev;
    private javax.swing.JTextField jTextFieldId_aluno;
    private javax.swing.JTextField jTextFieldJan;
    private javax.swing.JTextField jTextFieldJul;
    private javax.swing.JTextField jTextFieldJun;
    private javax.swing.JTextField jTextFieldMai;
    private javax.swing.JTextField jTextFieldMar;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNov;
    private javax.swing.JTextField jTextFieldOut;
    private javax.swing.JTextField jTextFieldOut1;
    private javax.swing.JTextField jTextFieldset;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
 jTextFieldNome.setText("");
 jTextFieldMar.setText("");
 jTextFieldAbr.setText("");
 jTextFieldMai.setText("");
 jTextFieldJun.setText("");
 jTextFieldJul.setText("");
 jTextFieldAgosto.setText("");
jTextFieldset.setText("");
jTextFieldOut.setText("");
jTextFieldNov.setText("");
jTextFieldDez.setText("");
jTextFieldJan.setText("");
jTextFieldFev.setText("");
jTextFieldId_aluno.setText(""); 
jTextFieldCodigo.setText("");
    }
}

