/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoclik.aluno;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import infoclik.fachada.Fachada;
import java.awt.EventQueue;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Cledson
 */
public class TelaCadastroAluno extends javax.swing.JFrame {

   
    public JFrame frmCadastroAluno;
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaCadastroAluno frame = new TelaCadastroAluno();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
    
    
    /**
     * Creates new form TelaCadastroAluno
     */
    public TelaCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelData_nasc = new javax.swing.JLabel();
        jTextFieldData_nasc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jTextFieldSexo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelEst_civil = new javax.swing.JLabel();
        jTextFieldEst_civil = new javax.swing.JTextField();
        jLabelEndereço = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelEntidade = new javax.swing.JLabel();
        jTextFieldEntidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelResponsavel = new javax.swing.JLabel();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRg = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelHorario_optado = new javax.swing.JLabel();
        jTextFieldHorario_optado = new javax.swing.JTextField();
        jLabelData_pag = new javax.swing.JLabel();
        jTextFieldData_pag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelObs = new javax.swing.JLabel();
        jTextFieldObs = new javax.swing.JTextField();
        jLabelData_cad = new javax.swing.JLabel();
        jTextFieldData_cad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCpfRes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCursoContrato = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldValorParcela = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldValorExtenso = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldParcelas = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aluno(a)");

        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelData_nasc.setText("Data de Nascimento:");

        jTextFieldData_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldData_nascActionPerformed(evt);
            }
        });

        jLabel1.setText("ex: 22/02/2016");

        jLabelSexo.setText("Sexo:");

        jTextFieldSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexoActionPerformed(evt);
            }
        });

        jLabel2.setText("F ou M");

        jLabelEst_civil.setText("Estado Civil:");

        jTextFieldEst_civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEst_civilActionPerformed(evt);
            }
        });

        jLabelEndereço.setText("Endereço:");

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jLabelBairro.setText("Bairro:");

        jLabelEntidade.setText("Entidade:");

        jLabel3.setText("Cidade:");

        jLabelCep.setText("Cep:");

        jLabelTelefone.setText("Telefone:");

        jLabelResponsavel.setText("Responsável:");

        jLabel4.setText("Rg:");

        jTextFieldRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRgActionPerformed(evt);
            }
        });

        jLabelCpf.setText("Cpf:");

        jLabelHorario_optado.setText("Horário Optado:");

        jLabelData_pag.setText("Data Pagamento:");

        jLabel5.setText("ex: 22/02/2016");

        jLabelObs.setText("Obs:");

        jLabelData_cad.setText("Data Cadastro:");

        jLabel6.setText("ex: 16 de Abril de 2016");

        jLabel7.setText("ex: 09923487586");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButton1.setText("Contrato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Informações Complementares para a criação do contrato");

        jLabel9.setText("Cpf responsável:");

        jLabel10.setText("Curso:");

        jLabel11.setText("Valor Total do Curso:");

        jLabel12.setText("Valor da Parcela:");

        jLabel13.setText("ex: R$ 75,00");

        jLabel14.setText("Valor da parcela por extenso: ");

        jLabel15.setText("Ex: (Setenta e cinco reais)");

        jLabel16.setText("Nº Parcelas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(245, 245, 245))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCpfRes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCursoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSair)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel15)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEst_civil)
                                        .addComponent(jLabelEntidade))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldEst_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelEndereço))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel3)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelCep)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelBairro)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTelefone)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelHorario_optado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHorario_optado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelData_pag)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldData_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelObs)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldObs)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelData_nasc)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldData_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jLabelSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelResponsavel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCpf)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelData_cad)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldData_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData_nasc)
                    .addComponent(jTextFieldData_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelSexo)
                    .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEst_civil)
                    .addComponent(jTextFieldEst_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEndereço)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEntidade)
                    .addComponent(jTextFieldEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCep)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResponsavel)
                    .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCpf)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorario_optado)
                    .addComponent(jTextFieldHorario_optado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData_pag)
                    .addComponent(jTextFieldData_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelObs)
                    .addComponent(jTextFieldObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData_cad)
                    .addComponent(jTextFieldData_cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCpfRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCursoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldValorExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonSair)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldData_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldData_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldData_nascActionPerformed

    private void jTextFieldSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexoActionPerformed

    private void jTextFieldEst_civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEst_civilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEst_civilActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRgActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        cadastroAluno();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        documento();
    }//GEN-LAST:event_jButton1ActionPerformed

   
      
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelData_cad;
    private javax.swing.JLabel jLabelData_nasc;
    private javax.swing.JLabel jLabelData_pag;
    private javax.swing.JLabel jLabelEndereço;
    private javax.swing.JLabel jLabelEntidade;
    private javax.swing.JLabel jLabelEst_civil;
    private javax.swing.JLabel jLabelHorario_optado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldCpfRes;
    private javax.swing.JTextField jTextFieldCursoContrato;
    private javax.swing.JTextField jTextFieldData_cad;
    private javax.swing.JTextField jTextFieldData_nasc;
    private javax.swing.JTextField jTextFieldData_pag;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEntidade;
    private javax.swing.JTextField jTextFieldEst_civil;
    private javax.swing.JTextField jTextFieldHorario_optado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldObs;
    private javax.swing.JTextField jTextFieldParcelas;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldRg;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldValorExtenso;
    private javax.swing.JTextField jTextFieldValorParcela;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
jTextFieldNome.setText("");
jTextFieldData_nasc.setText("");
jTextFieldSexo.setText("");
jTextFieldEst_civil.setText("");
jTextFieldEndereco.setText("");
jTextFieldBairro.setText("");
jTextFieldEntidade.setText("");
jTextFieldCidade.setText("");
jTextFieldCep.setText("");
jTextFieldTelefone.setText("");
jTextFieldResponsavel.setText("");
jTextFieldRg.setText("");
jTextFieldCpf.setText("");
jTextFieldHorario_optado.setText("");
jTextFieldData_pag.setText("");
jTextFieldObs.setText("");
jTextFieldData_cad.setText("");
    }

    private void cadastroAluno() {
    String nome =   jTextFieldNome.getText(); 
String data_nasc = jTextFieldData_nasc.getText();
String sexo = jTextFieldSexo.getText();
String est_civil = jTextFieldEst_civil.getText();
String endereco = jTextFieldEndereco.getText();
String bairro = jTextFieldBairro.getText();
String entidade = jTextFieldEntidade.getText();
String cidade = jTextFieldCidade.getText();
String cep = jTextFieldCep.getText();
String telefone = jTextFieldTelefone.getText();
String responsavel = jTextFieldResponsavel.getText();
String rg = jTextFieldRg.getText();
String cpf = jTextFieldCpf.getText();
String horario_optado = jTextFieldHorario_optado.getText();
String data_pag = jTextFieldData_pag.getText();
String obs = jTextFieldObs.getText();
String data_cad = jTextFieldData_cad.getText();



Aluno aluno = new Aluno(nome, data_nasc, sexo, est_civil, endereco, bairro, entidade, cidade, cep, telefone, responsavel, rg, cpf, horario_optado, data_pag, obs, data_cad);
    
    
    try {
	
		Fachada.getInstance().alunoCadastrar(aluno);
		
		JOptionPane.showMessageDialog(frmCadastroAluno, "Cadastro Realizado com sucesso!");
		this.limparCampos();
	
	} catch (infoclik.aluno.CPFInvalidoException e) {
		JOptionPane.showMessageDialog(frmCadastroAluno, e.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
	} catch (AlunoJaCadastradoException e){
		JOptionPane.showMessageDialog(frmCadastroAluno, e.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
	} catch (infoclik.aluno.CampoObrigatorioException e) {
		JOptionPane.showMessageDialog(frmCadastroAluno, e.getMessage(), " ERRO " , JOptionPane.ERROR_MESSAGE);
	} catch (SQLException e) {
		JOptionPane.showMessageDialog(frmCadastroAluno, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
	}catch (Exception e){
		JOptionPane.showMessageDialog(frmCadastroAluno, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
	}
    
    }

    public void documento(){
     System.out.println("\nExemplo de como criar um arquivo PDF");
        
        // criando um objeto da classe Document
        Document documento = new Document();
        
        try {
            
            //Aqui começamos a utilizar as classes do iText: o documento
            //criado acima será     
            //direcionado para um arquivo PDF.         
    
   PdfWriter.getInstance(documento, new FileOutputStream("D:\\contratoinfoclik.pdf"));
            
            //abrindo o documento.
            documento.open();
            
            //adicionando um novo paragrafo.
            documento.add(new Paragraph("INFOCLIK - Cursos Profissionalizantes "));
             documento.add(new Paragraph("Contrato de Prestação de Serviços Educacionais")); 
             documento.add(new Paragraph(" "));
             documento.add(new Paragraph(" "));
            documento.add(new Paragraph("INSTRUMENTO PARTICULAR")); 
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Considerando os artigos 1° inciso IV, 5° inciso II, 173° inciso II e III, e 209°, todos da Constituição Federal; artigos 104, 185, 427, 475, 476, 477 840 do código Civil Brasileiro; da Lei N° 8.078/90 (Código do Consumidor); Lei 9.069/95."));
             documento.add(new Paragraph(""));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Os signatários firmam o presente CONTRATO para a prestação de serviços educacionais, que entre si fazem "+jTextFieldResponsavel.getText()+ " portador de CPF " + jTextFieldCpfRes.getText()+ " assume todas as obrigações e responsabilidade do aluno " +jTextFieldNome.getText() +", doravante denominado (a) contratante."));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("A JONAS LOURENÇO DE OLIVEIRA JÚNIOR – ME com sede na Av. José Mendonça Bezerra, 167 Centro – Belo Jardim – PE, inscrita sob o C.N.P.J. 02.719.046/0001-90, doravante denominada CONTRATADA, mediante as cláusulas e condições previstas abaixo."));
           
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("CLÁUSULA I – O objeto do presente CONTRATADO é a prestação de serviços educacionais correspondente ao " + jTextFieldCursoContrato.getText()+ " ou cursos adicionais, a ser ministrado em conformidade como previsto nas condições e regimento da empresa, para o aluno e beneficiário. "));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("COMPROMISSO DA CONTRATADA"));
            documento.add(new Paragraph(" "));
         
            documento.add(new Paragraph("CLÁUSULA II – A CONTRATADA assegura ao CONTRATANTE uma vaga no seu corpo discente, conforme a cláusula I, ministrando o ensino através de aulas e demais atividades escolares, cujo planejamento pedagógico atenda ao disposto."));
            documento.add(new Paragraph(" "));
           
            
            documento.add(new Paragraph("§ 1°- As aulas serão ministradas nas salas de aula ou em locais que a CONTRATADA indicar, tendo em vista a natureza do conteúdo e técnicas pedagógicas que se fizerem necessárias."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("§ 2°- Reserva-se a CONTRATADA o direito de cancelar ou remanejar qualquer turma cujo número de alunos seja inferior ou igual a 08, proporcionando ao aluno neste caso, o direito de ocupar uma vaga em outra turma similar, no mesmo ou em outro turno, desde que esta exista."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("§ 3°- A CONTRATADA reserva-se o direito de efetuar a fusão de turmas cujo número de alunos não atenda ao parágrafo segundo para minimizar os efeitos de evasão, podendo acarretar em atrasos no calendário de aula programado"));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("§ 4°- Fornecer o material didático ao contratante, gratuitamente desde que o mesmo esteja em dia com suas mensalidades."));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("§ 5°- Em caso de inadimplência a contratada reserva-se o direito de suspender às aulas do aluno acima citado, assim como, o direito de participar de qualquer sorteio ou promoção, bem como não emitir o certificado de conclusão do referido curso."));
           documento.add(new Paragraph(" "));
           
            documento.add(new Paragraph("§ 6°- Após matrícula, o aluno terá o prazo de 24 horas para desistir do curso, somente neste caso, ficará isento da taxa de desistência, contudo não haverá devolução da taxa referente à matrícula."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("§ 7°- A CONTRATADA não se responsabiliza por objetos dados, furtados ou danificados do CONTRATANTE ou de TERCEIROS dentro ou fora do estabelecimento."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("COMPROMISSO DO CONTRATANTE"));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("§ 1°- Respeitar as regras de conduta interna, ao instrutor e aos colegas;"));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("§ 2°- Fazer o pagamento de "+ jTextFieldValorTotal.getText()+ " referente ao curso ora citado à vista ou em"+ jTextFieldParcelas.getText() +  "parcelas de "+ jTextFieldValorParcela.getText()+ " com desconto de R$ 5,00, caso efetue o pagamento na secretaria até o dia 05 com vencimento 31 de cada mês;"));
            documento.add(new Paragraph(" "));
           
            documento.add(new Paragraph("§ 3°- Pagar após o vencimento, multa de 2% e juros de 0,20 ao dia de atraso."));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("§ 4°- Em caso de DESISTÊNCIA, o aluno ou responsável deverá quitar as parcelas que estiverem em atraso e pagar uma multa de "+jTextFieldValorParcela.getText() +" " +jTextFieldValorExtenso.getText()+", caso não seja paga implicará na imediata inscrição do CONTRATANTE no Serviço de Proteção ao Crédito (SPC)."));
           
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("§ 5°- Após matrícula, aluno terá o prazo de 24 horas para desistir do curso, onde somente neste caso, ficará isento da taxa de desistência, contudo não haverá a devolução da taxa referente à matrícula."));
            documento.add(new Paragraph(" "));
          
            documento.add(new Paragraph("§ 6°- Caso o CONTRATANTE abandone o curso sem efetuar a desistência do mesmo, no prazo de um mês, poderá contratada cobrá-lo judicialmente todas as parcelas não pagas inclusive às vencidas."));
            documento.add(new Paragraph(" "));
           
            documento.add(new Paragraph("§ 7°- O CONTRATANTE deverá ter freqüência de 75% e média igual ou superior a 7,0 para atingir a aprovação no curso e recebimento do certificado de conclusão."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("§ 8°- Caso o CONTRATANTE efetue o pagamento após o vencimento o mesmo perderá ao desconto promocional automaticamente."));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("Fica eleito o fórum da comarca de Belo Jardim – PE para dirimir quaisquer dúvidas oriundas do presente termo. E por estarmos justos e acordados, "));
            documento.add(new Paragraph("                                                                                                "+jTextFieldData_cad.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("____________________________________ "));
            documento.add(new Paragraph("           Testemunha                 ")); 
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("____________________________________  "));
            documento.add(new Paragraph("           Testemunha                 "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("____________________________________  "));
            documento.add(new Paragraph("JONAS LOURENÇO DE OLIVEIRA JÚNIOR – ME"));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("____________________________________  "));
            documento.add(new Paragraph("    " + jTextFieldResponsavel.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Rua José Mendonça Bezerra, 167 – Centro"));
            documento.add(new Paragraph("Belo Jardim – PE (81) 3726 – 5408"));
            documento.add(new Paragraph("CNPJ 02.719.046/0001 - 90"));
            JOptionPane.showMessageDialog(frmCadastroAluno, "Contrato criado com sucesso!");
         Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "D:\\contratoinfoclik.pdf"});       
        }
        catch(DocumentException de) {
            System.err.println(de.getMessage());
        }
        catch(IOException ioe) {
            System.err.println(ioe.getMessage());
        }
        
        //fechando o documento.
        documento.close();
          
    
}

 
}
